### PR TITLE
Rssfeeds

### PR DESCRIPTION
**Pull request by redbeed**
Hello,

i add an rss viewer for the default view.
You can add multi RSS Feeds (Articles) and set the "change/update" time.

### CODE REVIEW

**Comment by kurtdb** [comment]
Could you compare your change to the current RSS-implementation? Maybe it's useful to add your ideas to that code?

**Comment by yaydogan** [comment]
@redbeed  Is it possible to add a config where users can choose between current display and the new display option you are adding? I think that would be cool.

**Comment by digitaldidge** [comment]
I was wondering if an image or logos could be displayed actually.

[(Facebook logo) RSS title/description ]

Maybe even being able to input a font awesome glyph? .svg, .png that sort of thing anyway :)

Hope it feeds an innovative idea for someone to invent :D

**Comment by evancohen** [comment]
Hey @redbeed thanks for taking the time to put this together 👍 I'm closing this PR because we have another RSS implementation now. There are definitely some improvements that can be made with our implementation, so feel free to send another PR updating the existing code. Let me know what you think.

**Pull request closed without merging**
