### PR TITLE
RSS Service

### PR DESCRIPTION
**Pull request by yaydogan**
I created an RSS-service which allows retrieving RSS feeds from multiple sources. Implementation is based off of Evan's rss branch.

### CODE REVIEW

**Comment by FrankMatheis** [comment]
@yaydogan: I tried your changes but came up with this
file:///home/pi/Desktop/2016-03-15-180014_1776x952_scrot.png

**Comment by yaydogan** [comment]
@evancohen  please hold off the merge. @FrankMatheis  is having an issue with this code and I am looking at it. I will let you know once we get it working properly.

**Comment by shoaibuddin** [comment]
Working for me but @evancohen wants to use angular feeds

**Comment by yaydogan** [comment]
@shoaibuddin thanks for confirming it is working for you. It works for me too. We will focus on config file to see if that is the issue for @FrankMatheis.

**Comment by evancohen** [comment]
Angular Feeds will allow custom templates, which might be nice. I think the issue that @FrankMatheis might be having is that you are checking for a field that doesn't exist. 

If you can fix this for Frank then I'm cool with merging this in.

**Comment by shoaibuddin** [comment]
How about having an array of Google news section wise and set commands to "Show me tech news"? ....

**Comment by shoaibuddin** [comment]
@yaydogan It works on Mac but not on Raspi.

**Comment by yaydogan** [comment]
Let me debug on RPI, I have been developing/testing on PC. Is there any errors in console?

**Comment by shoaibuddin** [comment]
@yaydogan Never mind it works!. There was something wrong with my connection.

**Comment by GobleSt** [comment]
@yaydogan I am interested in the RSS service and trying to use your branch.  I get:
`> smart-mirror@0.0.1 start /home/pi/smart-mirror`
`> electron main.js`

`(electron) companyName is now a required option to crashReporter.start`
`true`
`(electron) loadUrl is deprecated. Use loadURL instead.`
`[2974:0612/064428:ERROR:logging.h(810)] Failed to call method:` `org.freedesktop.NetworkManager.GetDevices: object_path= /org/freedesktop/NetworkManager:` `org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not` `provided by any .service files`

I am sure it is me, so what am I doing wrong?

**Comment by yaydogan** [comment]
@GobleSt  Are you using rss-dev branch? I will take a look.

**Comment by GobleSt** [comment]
I didn't see rss-dev in the list so just rss.  
`pi@smartmirror:~/smart-mirror $ git branch -a`
 ` master`
`* rss`
  `remotes/origin/HEAD -> origin/master`
  `remotes/origin/HomeAssistant`
  `remotes/origin/cache-data`
  `remotes/origin/cordova`
 ` remotes/origin/dev`
  `remotes/origin/evancohen/keyword-spotting`
 ` remotes/origin/gh-pages`
 ` remotes/origin/gulp`
 ` remotes/origin/installer`
 ` remotes/origin/master`
 ` remotes/origin/python`
`  remotes/origin/rss`
 ` remotes/origin/timebox`
 ` remotes/origin/todoist`
`  remotes/origin/travis`

Should I try for rss-dev?

**Comment by GobleSt** [comment]
I'm new to github so give me a moment to figure out how to do that and I will get right back to ya... (told you it was me!)

**Comment by GobleSt** [comment]
OK.... I manually DL the files and copied them over to the directory.  I get:

`Config Error:  Syntax Error.`
`Looks like there's an error in your config file: Unexpected token >>>`

I tried the example config and receive the same....?

**Comment by GobleSt** [comment]
OK.  So it looks like it is having an issue with `>>>>>>> refs/remotes/evancohen/master` in the config.example.js  commenting out that line resolves the issue and RSS is working!!

**Comment by GobleSt** [comment]
Is there a way we can get the greeting to remain centered instead of jumping up and down every time the feed updates?

**Comment by yaydogan** [comment]
@GobleSt  Thanks for catching the issue with config file. I fixed that. For the greeting to remain centered, you can try this quick fix. Find the following line in controller.js:

setTimeout(function(){ $scope.news = RssService.getNews(); $scope.shownews = true; }, 990);

Replace timer value 990 with something like 800. The news will fade in/out quicker and greeting shouldn't jump. There are other ways for sure and I can look at other options for a better solution.

**Comment by GobleSt** [comment]
Currently creating a backup of my SD card so as soon as I am done I will give it a try.  My preference would be to MOVE the greeting to the bottom above the news feed and leave the center of the mirror clean for facial viewing....

**Comment by GobleSt** [comment]
Greeting still jumps up and down after making the speed change.  I think the layout just needs some tweaking.  I would like to be able to modify the features layout in the config.js like telling the greeting to be at the bottom above the RSS or swap the calendar to the right and the weather to the left....just for customization....

**Comment by evancohen** [comment]
@yaydogan looks good to me. I would specify a min height on the news area to avoid the issue that @GobleSt is having.

**Comment by yaydogan** [comment]
@evancohen  You can merge this in now. I will fix the css sometime this week.

**Comment by ikucukkaya** [comment]
Great work! @yaydogan hocam uzun zamandır türk müsünüz acaba diye düşünüyordum şu an etiketlerken fark ettim ki öyleymiş bir de türkçe teşekkür edeyim dedim :D

**Comment by evancohen** [comment]
Merged! Thanks again @yaydogan :rocket:

**Comment by yaydogan** [comment]
@GobleSt @ikucukkaya @evancohen   Thanks for all your help verifying the merge. Off to the next project :)

**Pull request merged**
