### PR TITLE
GIRI: Weather Forecaster

### PR DESCRIPTION
**Pull request by ghilo17**
I just want this to be a mini weather station, its quite easy but please help me and approve my request thanks

### CODE REVIEW

**Comment by kurtdb** [comment]
Not sure why we should approve the pull request: there are merge errors and you have added nothing yourself? Closing this for now, as it is unsure what the goal is.

**Comment by ghilo17** [comment]
sir how can I install it on my own pi, with my own revisions without
affecting yours??? thats what i wanted to do, please help\
i dont change anything at first because im afraid to change it and can
affect your programs

**Comment by kurtdb** [comment]
Read the docs how to install it on your raspberry pi: http://docs.smart-mirror.io/.

If you need help installing the application, it might be best to just join us on the gitter channel: https://gitter.im/evancohen/smart-mirror.

**Comment by ghilo17** [comment]
oh yes, i already installed it but it was based on your own codes and
configurations styles and layout, i want to change it customize it on my
own taste of style, how can i do that? without affecting yours but still it
will be apply on my mirror? thanks

**Comment by ghilo17** [comment]
theres no any explanation telling that i can make new things with just for
me, and will not affect yours

**Comment by kurtdb** [comment]
As long as you do not commit your changes, everything should be ok. Downside is that you will not be able to update the application.

**Comment by evancohen** [comment]
If you create your own fork you can commit as much as you want... just don't create PRs on this repository. You can always rebate new changes from upstream later. Unsure where the confusion is coming from here.

**Pull request closed without merging**
