### PR TITLE
remove projectId requirement in config.

### PR DESCRIPTION
**Pull request by justbill2020**
sonus.js will now use the keyfile to load the project ID.

sonus.js will now check to make sure the model file exists and default to snowboy.umdl if it does not.

prepping for config.js by adding the capability of using config.general.language as well as config.language

### CODE REVIEW

**Comment by justbill2020** [comment]
@evancohen this is ready to go... tested and functional... one less thing to troubleshoot on gitter... :shipit:

**Comment by evancohen** [comment]
I'm assuming that `config-index.js` is a part of your remote UI changes, in which case it won't actually work on `dev` yet.

**Comment by justbill2020** [comment]
its frustrating that i missed that when patching it to the current dev... ugh..... ok fixed it we're good now

**Comment by evancohen** [comment]
Made a small tweak to avoid redundancy. Take a look and then squash and merge if it looks good to you,

**Comment by justbill2020** [comment]
looks good... merge and squashed to dev... i'm stealing those changes to the configUI branch...

**Pull request merged**
