### PR TITLE
Config refresh - make configuration of the mirror more versatile and easier to understand

### PR DESCRIPTION
**Pull request by evancohen**
This will be a breaking change to the existing `config.js` file. The main goal if this change is two fold. 

1. Make it easier for people to fill out. This is done by:
 - Breaking the configuration into more understandable peaces
 - Moving it to the root of the `smart-mirror` directory
2. Make it more extensible
 - By making the configuration more modular it should make it much easier to extend (more API keys, optional values, etc)

Feel free to give any feedback you have. I'm sure there are more improvements that can be made here.

### CODE REVIEW

**Comment by yaydogan** [comment]
@evancohen This configuration file looks great. Few suggestions:

- Can you add a config option to disable services? e.g. people who doesn't have Hue can disable it.
- Can you add refresh timer per service? I would like to update weather and calendar more often than others for instance. 

Thanks!

**Comment by kurtdb** [comment]
Another option is a bit less user friendly to start with, but it will keep the configuration seperate:

Define a config.json file that contains all the settings. Next to that, on application startup read the file (through an ajax request to the local file system) and set angular constants using the $provider. That way all the settings are known in the application, the configuration is never overwritten and the code is testable.

The biggest downside is that we have to document each and every setting that people have to configure in the json-file. (might be a pain, since I foresee a lot of questions regarding this after finishing it)

**Comment by evancohen** [comment]
@kurtdb I think that's an excellent long term plan (or at least something like that). @yaydogan agreed with these suggestions, I'll take a crack at them tonight.

**Comment by yaydogan** [comment]
@evancohen Awesome. Thanks a lot!

**Comment by evancohen** [comment]
Based on the comments in #60 I'm just going to merge this in and address optional configuration and disabling of services in another PR. It will likely be a pretty big change touching a lot of files so breaking it into another one is probably the right thing to do.

**Pull request merged**
