### PR TITLE
Add: add bus Rennes service

### PR DESCRIPTION
**Pull request by overfl0w11**
####  Description
Service for bus in Rennes, France (réseau star)

####  Fixes Related issues
- None

####  Checklist
- [X] I have read and understand the CONTRIBUTIONS.md file
- [X] I have searched for and linked related issues
- [X] I have added config.schema.json file if config option are required.
- [X] I am NOT targeting master branch

### CODE REVIEW

**Comment by evancohen** [comment]
Thanks for this contribution! I've been really busy this week and haven't had the chance to review just yet. A preliminary look over everything and it looks awesome.

I'll take a look tomorrow or Sunday 🏃

**Comment by overflOw11** [comment]
Don't worry ! I've been busy this week too. I'm working on the Todoist integration. A new PR will come soon.
Let me know if there is something to fix in these PR.

**Comment by justbill2020** [comment]
Thanks for the contribution we love getting these! I'm not sure this will be super useful for everyone, having said that I think some people will find it super useful. So we're going to start working on finding ways to allow people to bring 3rd party plugins into the mirror... When we implement this we're going to have you make this so that it can be included so people can add it using that functionality...

**Comment by evancohen** [comment]
Totally agreed with @justbill2020 Not sure if we should close this out until we get plugins working or just leave it open for people who are interested to rebase onto their mirror.

**Comment by justbill2020** [comment]
you know me i like having a clean PR list... but we can leave it for sure...

**Comment by overflOw11** [comment]
Yeah of course this PR will not be usefull for everybody. I agree, plugin integration will be great. Do whatever you want with this PR. I keep the code on my own repo. 
Can't wait for the plugin integration ! Let me do if you wan't some help.

**Comment by sdetweil** [comment]
need to redo dev branch

**Pull request closed without merging**
