### PR TITLE
make traffic service more globally

### PR DESCRIPTION
**Pull request by KyoungjunPark**
OK, I changed the base as dev not master.
But, I got a message that "Can't automatically merge".
Is it fine?
updated pull request: #459

### CODE REVIEW

**Comment by justbill2020** [comment]
@KyoungjunPark you'll need to manually resolve conflicts before we can merge the PR. Most likely you created the branch you worked on from master which is always a few commits behind dev so we can test prior to merging with master. 

I did the same thing when I started contributing. It's all part of the learning curve.

**Comment by evancohen** [comment]
No worries, I can sort this out on my end if you dont know how to fix it :)

**Comment by KyoungjunPark** [comment]
So, Basically do i must develop using branch splitting from dev not master?

**Comment by justbill2020** [comment]
That would be best practice. And you'll want to make sure your dev branch is up to date with the dev branch from @evancohen's repo... looks like Evan has you covered on this one though...

**Comment by KyoungjunPark** [comment]
Oh, Thank you. I'll do that later.

**Comment by KyoungjunPark** [comment]
So do i close this pull request?

**Comment by evancohen** [comment]
Nah, keep it open - I just haven't had a chance to do this yet.

**Comment by KyoungjunPark** [comment]
OK! Thank you for your respond!

**Comment by evancohen** [comment]
Thanks @KyoungjunPark!

**Pull request merged**
