### PR TITLE
Added service to track tvshows

### PR DESCRIPTION
**Pull request by glcohen**
Service to track when the next episode of your favorite tv shows is going to air. Add a list of your TV shows in config.js, and they'll show up under stocks with their name and the next air date. If a next air date isn't available the show won't be displayed.

Makes use of the free API http://epguides.frecar.no/

### CODE REVIEW

**Comment by evancohen** [comment]
Awesome! Can you resolve these conflicts so I can merge?

**Comment by justbill2020** [comment]
This is an awesome add on!

**Comment by glcohen** [comment]
I've copied in the changes manually from your dev branch a few times and tried cleaning up the whitespace but it's still complaining. Can you lend a hand or let me know how to better handle resolving it?

**Comment by chanjungkim** [comment]
I installed everything. and sonus seems okay. Billed google speech and got API and applied in the config.json from smart mirror..
But 'what can I say?' isn't working.. what should I do???

**Pull request closed without merging**
