### PR TITLE
Add simple sound-cloud visualizer

### PR DESCRIPTION
**Pull request by mojosoeun**
Hi
I added simple sound-cloud visualizer :)

### CODE REVIEW

**Comment by evancohen** [comment]
It's really difficult to review this because you've changed the indentation of nearly every line. Can you revert your tabbed spacing so I can take a look at this? I think it's a really good idea :)

**Comment by mojosoeun** [comment]
Ok :) I will revert my tabbed spacing.

**Comment by mojosoeun** [comment]
@evancohen  I changed the code :)

**Comment by evancohen** [comment]
Awesome, thanks! I took a look and the only thing that seems off to me is that there are now two services for SoundCloud. I think it'd be a good idea to move the visualizer into the existing service, what do you think?

**Comment by mojosoeun** [comment]
I agree, it'd be a good idea! I will do this today.

**Comment by mojosoeun** [comment]
I move the visualizer service into soundcloud service :)

**Pull request merged**
