### PR TITLE
make possible to set the location

### PR DESCRIPTION
**Pull request by redbeed**
Hello,

simple but important for bugs with browser location detection.

### CODE REVIEW

**Comment by evancohen** [comment]
Why is this needed? Is there a problem with geolocation? If that's the case then we should be fixing geolocation, not adding complexities to the config.

**Comment by redbeed** [comment]
Yes, but for user without browser geo-detection?
You can disable this for your Ethernet.

Example  tow: the detected geo position is near me, but in the wrong country.

**Comment by Robiv8** [comment]
Oh yes! My geolocation is also wrong, The map is 15km from my Location.

**Comment by evancohen** [comment]
@redbeed can you fix the conflicts here? After giving it some thought it's probably a good idea to merge.

**Comment by Robiv8** [comment]
Yes! i agree with redbeet. My map is also ~10km from my location.

**Comment by evancohen** [comment]
@redbeed please fix the merge conflicts so I can merge this in :)

**Comment by redbeed** [comment]
@evancohen i will do this in the next few days

**Comment by evancohen** [comment]
Sorry this took so log @redbeed, all merged in!

**Pull request merged**
