### PR TITLE
Fitbit integration

### PR DESCRIPTION
**Pull request by Shogan**
Sorry about the old PR against the wrong branch! This should now be to merge into your dev branch and everything should be good to merge with no conflicts now :smile: 

More detail about this PR on the old PR at https://github.com/evancohen/smart-mirror/pull/154

### CODE REVIEW

**Comment by evancohen** [comment]
So I'm trying to move to a model where if a service is not in the config it doesn't crap out. We should not be using enabled/disabled in the config - if it's not there we can assume it's disabled.

Put simply if 
``` javascript
if(typeof config.fitbit =! 'undefined'){
    // do express and Fitbit things
}
``` 

Express should not start unless the correct value in the config exists (this will be the case for most users, since not everyone has Fitbit).

If at all possible all of this logic should exist in the service (although it's reasonable to expect that some things must live in the controller)

screen shot 2016-03-23 at 8 17 02 pm

Also, only show this message if fitbit is enabled - we don't want to pollute the console :)

Thanks!!!

**Comment by Shogan** [comment]
Got it - I'll sort out later on today! Thanks for the feedback :)

On 24 March 2016 at 03:25, Evan Cohen <notifications@github.com> wrote:

> So I'm trying to move to a model where if a service is not in the config
> it doesn't crap out. We should not be using enabled/disabled in the config
> - if it's not there we can assume it's disabled.
>
> Put simply if
>
> if(typeof config.fitbit =! 'undefined'){
>     // do express and Fitbit things
> }
>
> Express should not start unless the correct value in the config exists
> (this will be the case for most users, since not everyone has Fitbit).
>
> If at all possible all of this logic should exist in the service (although
> it's reasonable to expect that some things must live in the controller)
>
> [image: screen shot 2016-03-23 at 8 17 02 pm]
> <https://cloud.githubusercontent.com/assets/1198365/14007474/54ba15f6-f134-11e5-8046-5fc8ebf97dff.png>
>
> Also, only show this message if fitbit is enabled - we don't want to
> pollute the console :)
>
> Thanks!!!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/evancohen/smart-mirror/pull/180#issuecomment-200638160>
>



-- 
VMware vExpert 2012-2016
Shogan.tech <http://www.shogan.co.uk> - VMware, Cloud, Automation,
scripting blog
Hobbyist Coder <http://hobbyistcoder.com> - Programming and Game
Development blog

**Comment by Shogan** [comment]
@evancohen thanks for the feedback - completely agree on how it should operate smoothly if there is no fitbit configuration in config.js and how it should just work if the user adds a fitbit configuration section in. 

I've now made the appropriate changes and ensured everything works gracefully whether a user has setup a fitbit configuration section or not. 

I've also updated the Fitbit-README.md, but please feel free to remove this file after merging in this PR, and I'll create another PR against the docs.smart-mirror.io branch with this same information on setting up Smart Mirror with Fitbit :+1:

**Comment by Shogan** [comment]
Sorry about the other user - all the commits are from me - I work from two machines - InvincibleBoris is my other github user account I use on the other machine.

**Pull request merged**
