### PR TITLE
revert sonus to as master.. no changes required.. still need main.js recovery

### PR DESCRIPTION
**Pull request by sdetweil**
####  Fixes Related issues
- add related
- #670 

####  Checklist
- [ ] I have read and understand the CONTRIBUTIONS.md file
- [ ] I have searched for and linked related issues
- [ ] I have added config.schema.json file if config option are required.
- [ ] I am NOT targeting master branch

### CODE REVIEW

**Comment by evancohen** [comment]
I like the approach here to re-spin up the child process! I think this PR should target `dev` and be a part of the `0.0.21` release, right?

**Comment by sdetweil** [comment]
yes, forgot to use dev.. how to fix...

**Comment by sdetweil** [comment]
i had this done last year,  but the nudge from Evan on the fix for the sonus node module  got this surfaced again. really want it to be stable for users

**Comment by evancohen** [comment]
@sdetweil thanks for bribing this up again! I do need to bake this into Sonus (or the underlying audio library), but in the meantime I think it's a good idea to merge this in so that it's stable 👍

**Comment by sdetweil** [comment]
no.. i already submitted a PR on sonus lib to do the recovery...

**Pull request merged**
