### PR TITLE
Smart mirror patch 0.0.6

### PR DESCRIPTION
**Pull request by evancohen**
**What's in v0.0.6**

- Audio configuration script from @justbill2020 
- TV show service from @glcohen 
- Ability to use multiple different hotwords for activation (ex: "smart-mirror", "hey mirror", etc)
- Various improvements and bugfixes

### CODE REVIEW

**Comment by evancohen** [comment]
@justbill2020 mind taking a look over this? I've decided that every PR to master should get it's own version number - that way we'll have a better way to troubleshoot with folks.

**Comment by justbill2020** [comment]
I totally agree regarding the version... anything specific you want me to test/verify?

**Comment by evancohen** [comment]
I haven't had the chance to test the TV Show service 😨. Also, have you verified the audio config script? I want to add the docs for that. Everything else should be ok :)

**Comment by evancohen** [comment]
Are we all set on this?

**Comment by justbill2020** [comment]
give me a few to test the tv services... I got distracted with the feathub migration...

**Comment by justbill2020** [comment]
ok the tv service works and its my new favorite thing...

**Comment by justbill2020** [comment]
this is ready to merge when you're good to go...

**Pull request merged**
