### PR TITLE
Ov/todoist service

### PR DESCRIPTION
**Pull request by overflOw11**
####  Description
Todoist basic integration (consult project, add item to project, complete item in a project)

####  Fixes Related issues
N/A
####  Checklist
- [x] I have read and understand the CONTRIBUTIONS.md file
- [X] I have searched for and linked related issues
- [X] I have added config.schema.json file if config option are required.
- [X] I am NOT targeting master branch

### CODE REVIEW

**Comment by justbill2020** [comment]
DUDE!!! This is super AWESOME!!! just a few things to clear up first... 

Here's the errors from travis:
```
/home/travis/build/evancohen/smart-mirror/plugins/todoist/service.js
   28:2   error  Mixed spaces and tabs                          no-mixed-spaces-and-tabs
   34:41  error  'project' is defined but never used            no-unused-vars
   47:2   error  Mixed spaces and tabs                          no-mixed-spaces-and-tabs
   55:8   error  'response' is assigned a value but never used  no-unused-vars
  103:54  error  Unnecessary semicolon                          no-extra-semi
  103:54  error  Unreachable code                               no-unreachable
```

getting rid of the unused variables can just be done editing the files... after you clear up that... the easiest way to fix the spaces and tabs is to run `npm run test-fix` after that if you run `npm run test` it will output any thing else that would fail the test... if it just goes to the command prompt again in the terminal you're good to go... commit the changes and that should sync here and then re-run the tests on travis-ci... Then one of us will look over the overall PR and go from there...

any other questions we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

Thanks again man this is awesome!!!

**Comment by justbill2020** [comment]
BONUS POINTS !!!! 

Great work I just tested the `config.schema.json` file for the plugin and that's solid too!!!

**Comment by overflOw11** [comment]
Yeah, sorry ! I don't run thhe `npm run test` commans before create the PR.
I'm also find a little bug on the `completeTask()` function. I'm working on it and i'll update this PR soon.

**Comment by justbill2020** [comment]
cool... let me know when its ready and i'll take the status off "on hold"

**Comment by overflOw11** [comment]
Done ! Enjoy, and let me know if there is something wrong.

**Comment by justbill2020** [comment]
cool i'll look at it when i have a chance... @evancohen check this awesomeness out!!!

**Comment by evancohen** [comment]
Hype! I'll review&merge this weekend 🍰

**Comment by overflOw11** [comment]
@evancohen Your weekend is so long... Have you had time to review this PR ?

**Comment by evancohen** [comment]
Sorry! My fault. I've been super busy - this weekend. I promise!

**Comment by evancohen** [comment]
Thanks again! This looks great. Rebasing to `dev`.

**Pull request merged**
