### PR TITLE
Bower

### PR DESCRIPTION
**Pull request by nicolasmn**
Manage dependencies with [Bower](http://bower.io/) and insert them with [Wiredep](https://github.com/taptapship/wiredep)

### CODE REVIEW

**Comment by evancohen** [comment]
Great idea :) I use a modified version of Annyang though. Keep Annyang and I'll merge this in.

**Comment by nicolasmn** [comment]
A quick diff showed me you added interimResults to Annyang which I think is actually a pretty nice feature! Instead of maintaining a copy you should file a pull-request against [TalAter/annyang](https://github.com/TalAter/annyang) and see if it gets merged in.

However, in the meantime I'm cool with keeping the modified version :+1:

**Comment by evancohen** [comment]
I've been meaning to do that for ages but haven't gotten around to it. I'll file it tonight :)

I'll take a look at this once I get home and make sure everything looks good and then merge it. 

Thanks for the contribution!

**Comment by dardub** [comment]
I'm wondering why bower was needed. Most newer projects have stopped using it in favor of npm. All of the libraries we are using in bower are also available in npm.

**Comment by dardub** [comment]
Here's a good article on the subject. https://gofore.com/stop-using-bower/

I think if you've used bower in production I'm sure you've run into the issue of resolving version dependency conflicts. 

Also, currently bower only has one active maintainer and they are seeking funding to keep the project alive.

**Comment by evancohen** [comment]
I really just needed something for dependency management. I'm happy to use npm instead, but this was less work ;)
It seems that people have been having issues with the version of moment that's currentlyincluded with Bower, so at the very least I'll have to fix that.

**Pull request merged**
