### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by mkerfoot**
Add directions on how to;
        Start the smart-mirror at boot
        Hide the mouse when inactive

### CODE REVIEW

**Comment by evancohen** [comment]
@mkerfoot does using `unclutter` apply to Electron or just Chromium. If it's just electron then we shouldn't have that as a part of the instructions. Also, there seem to be conflicts here. Please resolve them so I can merge this in (if `unclutter` does indeed work for electron)

**Comment by MikeMuratore** [comment]
unclutter works. I installed it on mine forever ago

**Comment by evancohen** [comment]
Just checked, indeed it does. Excellent find @mkerfoot, and thanks for testing @MikeMuratore. The only thing here that is actually necessary to install is the unclutter package (`chromium` is pointless and `x11-xserver-util` should already be installed by default on Raspbian.

Also it looks like you've got a bunch of extra file change here (not just to the README) - can you double check that you're only committing changes relevant to the PR? Feel free to close this out out and open a new one if you'd like.

**Comment by evancohen** [comment]
Closing this stale PR. All of this stuff is in the documentation now :) Thanks!

**Pull request closed without merging**
