### PR TITLE
locales DE

### PR DESCRIPTION
**Pull request by FrankMatheis**
I am not sure about the hue commands because I can not test it

### CODE REVIEW

**Comment by javiersigler** [comment]
Hi @FrankMatheis, I will rename the file: de-de.js to de-DE.js to support the RFC 3066 http://www.i18nguy.com/unicode/language-identifiers.html

**Comment by evancohen** [comment]
Thanks @javiersigler :) 

@FrankMatheis make that change and I'll merge it in

**Comment by FrankMatheis** [comment]
changes made. 
Thank you @javiersigler and of course @evancohen !

**Comment by evancohen** [comment]
Closing this because @FrankMatheis created #143

**Pull request closed without merging**
