### PR TITLE
Add giphy api

### PR DESCRIPTION
**Pull request by mojosoeun**
add [giphy api](https://api.giphy.com/)

### CODE REVIEW

**Comment by evancohen** [comment]
Please fix these conflicts. giphy should be a part of the trigger phrase. Either "show me giphy *" or "giphy *". Saying something like "giphy dancing cat" is more specific to the functionality that it will perform. 

Also, please add the resulting command into Available Commands in `index.html`

**Comment by Shubham0209** [comment]
Great attempt @mojosoeun 
Gave it a try, but i found some problem with the display. The gif appears to be trimmed/cut from the top only a part of the gif is visible.

**Comment by mojosoeun** [comment]
I fixed command and added the resulting command in index.html. 
also i fixed some problem with the display.

**Comment by evancohen** [comment]
Awesome, looks like you still have a merge conflict though.

**Comment by mojosoeun** [comment]
oh sorry. i solved merge conflict

**Comment by mojosoeun** [comment]
I fixed merge conflict

**Comment by evancohen** [comment]
Looks good to me! Thanks @mojosoeun :)

**Pull request merged**
