### PR TITLE
Task/translation of texts

### PR DESCRIPTION
**Pull request by javiersigler**
Full translation of the texts

### CODE REVIEW

**Comment by evancohen** [comment]
This looks great! Really glad to get away from `document.write`.
I'll have time to test it out tonight and verify everything, but at a glance it looks awesome. 

It's a bit redundant to have multiple loc files for each language. Maybe we want to drop the xx-XX resources and just keep the xx. Then on https://github.com/evancohen/smart-mirror/pull/179/files#diff-41d794d24ff042b1f9ac211fc3f9f951R26 you could just use
``` javascript
config.language.substr(0, 2)
```
Thoughts?

**Comment by javiersigler** [comment]
I know it's absolutely awful to need to duplicate the translation files, I have tried to find a beautiful solution to this problem but there is always a pitfall.

The problem is always the location algorithm of the translation file. The possible solutions are:
a) Duplicate the default locale en-US.json to en.json. (the implemented solution), so adding a new locale only requires to add it to the folder locales.
b) Define the mapping of all the languages like the following:
```
$translateProvider
  .registerAvailableLanguageKeys(['en', 'de'], {
    'en_US': 'en',
    'en_UK': 'en',
    'de_DE': 'de',
    'de_CH': 'de'
  })
```
The main problem of this solution is every time a new locale is added requires to add the mapping here as well.

I haven't found any other alternative to solve this issue.

**Comment by evancohen** [comment]
Thanks for the detailed response! I think we should go with your suggestion to remove the territory part of the locale. If there comes a time that people really want territory specific localization then we can consider the other options you outlined. Thanks! :rocket:

**Comment by javiersigler** [comment]
:smirk:

**Comment by evancohen** [comment]
Great work! Thanks!

**Pull request merged**
