### PR TITLE
Made locales consistent

### PR DESCRIPTION
**Pull request by dehlen**
- Added full stops to all descriptions
- Localized non-german descriptions in de.json
- Changed wording of a few commands

This PR references #342.

### CODE REVIEW

**Comment by kurtdb** [comment]
You now have 2 pull requests concerning the localization. Might be best to bundle them to make sure there are no possible merge errors?

If you are sure there will be no issues, disregard my comment. I just want to make sure we're not breaking anything here.

**Comment by dehlen** [comment]
I made two PR's because one is for making localizations consistent the other one is because of changes concerning the fitbit implementation. I didn't want to merge UI Logic for the fitbit integration (in index.html) with localizing the soundcloud commands in de.json for example. However if it is wanted to have a single PR I can merge them into 1 PR.

Concerning your comment about breaking stuff. From my point of view everything should be fine with merging this PR's.

**Comment by kurtdb** [comment]
I merged the first PR, but it seems we now have merge conflicts. Which I was kinda expecting.

Could you try to take a look at it and fix the conflicts?

**Comment by dehlen** [comment]
Ok I had a look at this. The conflict occurs due to the description of the lights_action in the commands. In one PR I didn't have added a full stop to the description in this branch here i added one. 

I am referring to this particular line:
```
"description": "Control color and brightness of lights"
+"description": "Control color and brightness of lights."
```
. I was able to successfully merge into my local branch how should I proceed to make life easy for you ?

**Comment by dehlen** [comment]
I resolved the issues in the branch. Do you think you are now able to merge ?

**Pull request merged**
