### PR TITLE
add Electron options to config and startup 

### PR DESCRIPTION
**Pull request by sdetweil**
####  Description
new version of browsers have stopped autoplay of media, unless the user interacts with the web page somehow.  mirror users in general will never do that

the 'fix' is to add some electron commandline parms , which require code changes..

I have added config schema to hold the two know parms
disable cache for  image related apps
change autoplay-policy to 'no-user-gesture-required'

####  Fixes Related issues
#781 youtube autoplay no longer works
- issues here

####  Checklist
- [x] I have read and understand the CONTRIBUTIONS.md file
- [x] I have searched for and linked related issues
- [x] I have added config.schema.json file if config option are required.
- [x] I am NOT targeting master branch

### CODE REVIEW

**Comment by evancohen** [comment]
Do we really need to expose this in the remote config? shouldn't we just pass this argument regardless so people don't have to deal with it?

**Comment by sdetweil** [comment]
well, i thought so too, then had another user need to turn off image caching.
so how many others do we need? 

I'm ok with hard coding  

Its your call.

**Comment by evancohen** [comment]
What was the use case for turning it off? 

If we are going to provide it in the remote config then we definitely should have them configured by default

**Comment by sdetweil** [comment]
If u start 0.23, and ask show "me how to tie a tie". It pulls up the YouTube, but it no longer plays.

I can't get the defaults to work. They are coded in the _general schema file

**Comment by evancohen** [comment]
Sorry for the confusion, I meant the image caching! For getting the default to work correctly, fill out the config manually and check the generated schema - there might be something a little off.

**Comment by sdetweil** [comment]
Someone was overwriting their inage files, then reload, but got old image, as it was already loaded. U can hack by adding date to the file, but, now u have two images in cache. Eventually u will run out of memory

The defaults looks like what config generates. Like I said, don't understand why. Same issue on the plugin position change, which is why I created a separate file.

**Comment by sdetweil** [comment]
I also see this on my background image plugin. Load a few hundred images and u will crash

**Comment by evancohen** [comment]
For setting up default configs (which I think you were having trouble with) you'll want to use: https://github.com/evancohen/smart-mirror/blob/master/remote/.config.default.json

**Comment by evancohen** [comment]
For setting up default configs (which I think you were having trouble with) you'll want to use: https://github.com/evancohen/smart-mirror/blob/master/remote/.config.default.json

I'm still not convinced that this needs to be configurable, we can just hard-code the values and if people need to add additional runtime params they can just do it with code.

**Comment by sdetweil** [comment]
I understand.. just we seem to be fighting a new set of users that don't know editors or finding files..
but again, your call.  we need to set the parm either way.

**Comment by sdetweil** [comment]
lets do it the hard coded way.. new pr shortly

**Pull request closed without merging**
