### PR TITLE
add Johnny five support

### PR DESCRIPTION
**Pull request by justbill2020**
- [x] Added johnny-five support for Motion detection
- [x] corrected script executable permissions
- [x] added `raspi-monitor.sh` file in scripts folder which makes the auto-timer work over long periods
- [x] corrected unnecessary change to `pi-install.sh`
- [x] Add enable/disable motion control
- [x] ~~Add proximity mode~~ adding this mode will not work... this is more for distance only... all IR proximity units were included in motion class of johnny-five

### CODE REVIEW

**Comment by justbill2020** [comment]
@evancohen I DID IT! I DID IT!!! JOHNNY-FIVE integration draft 1... more to come...

**Comment by justbill2020** [comment]
@phelixz here's the PR i mentioned in http://feathub.com/evancohen/smart-mirror/+12

**Comment by evancohen** [comment]
Wooh! This looks good, but I'll want to give it a test before I merge - should have time to do that either later this week or over the weekend. 

Nice job dude :)

**Comment by justbill2020** [comment]
added a fix for the voice command "screen on" and "screen off"....

also on a side note I added execute privileges to the scripts with .sh extensions...

**Comment by justbill2020** [comment]
how's this one going @evancohen? i would love to get the fixes in for the autosleep functionality...

**Pull request merged**
