### PR TITLE
v0.0.14 Update

### PR DESCRIPTION
**Pull request by evancohen**
#### Hot new stuff:
- Home assistant display
- Catchy Stocks
- Better Portuguese 
- Better Korean
- Google Cloud Speech v1 endpoints

### CODE REVIEW

**Comment by justbill2020** [comment]
Revert that commit...

**Comment by evancohen** [comment]
Which one?

**Comment by justbill2020** [comment]
Yes 92a1811

**Comment by evancohen** [comment]
Should I fix before I merge or should we leave it for the next release?

**Comment by justbill2020** [comment]
next release is fine... just we might need to add a known issues in the readme... 

like right at the top...

#Current Release
###v0.0.14
#Known Issues
#650 
#647
#642 
#561

**Comment by evancohen** [comment]
Ooh, I super like that. Good call!

**Pull request merged**
