### PR TITLE
extended fitbitservcie to support device overview and sleep summary

### PR DESCRIPTION
**Pull request by R3dRuM**
One of the core features I use of fitbit is the sleeping summary as it remindes me to get more sleep ;-)
Another thing I always forget is to charge my fitibit charge hr. So checking the battery status before leaving the house is great.

### CODE REVIEW

**Comment by evancohen** [comment]
Can you please resolve these merge conflicts? Then I'll take a look. Thanks!

**Comment by kurtdb** [comment]
Also, try to change the getToday to make use of a moment.js date, since that can be easier to localize.
You added extra functionality to the traffic-service that isn't part of this PR, so it may be best to make a branch for these functionalities in the future. (to make sure you can cherry pick the things you want to merge)

**Comment by R3dRuM** [comment]
will do by the end of the week
@kurtdb yes... my bad. noticed this after I made the last commit to the fork. will use branches in future :)

**Comment by evancohen** [comment]
@R3dRuM Are you still working on this?

**Comment by R3dRuM** [comment]
Yes. Didn't have time to merge it yet. Buzz times. Sorry.

**Comment by evancohen** [comment]
Manually resolved conflicts and merged in 392b77499742567f0683977071dc89984cd7ea93

**Pull request closed without merging**
