### PR TITLE
add Hyperion support

### PR DESCRIPTION
**Pull request by 7h30n3**
I added support for Hyperion ( https://github.com/hyperion-project/hyperion ).
It supports multiple hyperion clients and multiple languages.

### CODE REVIEW

**Comment by evancohen** [comment]
Awesome idea :) I think there is a lot of shared logic in the hue-service. I would do the following:

- Merge the Hyperion service into the existing Hue service and rename it something like light-servive.
- Use the config to determine what service they actually want to use. (They can remain separate config objects or be merged into a parent like `lights`, I'll leave that up to you)
- Use the light group name to determine what service/light they want to manipulate.
- Handel the case that a single light group name may appear in both services and should update both services.
- If no light group is specified apply the update to both services.

How does that sound?

**Comment by 7h30n3** [comment]
Sounds good to me. Work In Progress ;)

**Comment by evancohen** [comment]
@7h30n3 Have you had a chance to take a look at this yet?

**Comment by 7h30n3** [comment]
@evancohen Yeah, I've got a plan how to structure the config.js and I know how the code of the light-service.js has to look like. But I didn't have the to implement it yet. Sorry.

**Comment by evancohen** [comment]
No worries! Let me know if I can help at all :)

**Comment by 7h30n3** [comment]
As @evancohen suggested I merged the hyperion and hue services.
Everythings works fine for me, but I just had an hue emulator so somebody should test it with a real hue bridge.
Have fun :)

**Comment by evancohen** [comment]
Awesome! Does each Hyperion really have an IP address and port for each bulb? It makes the config a little confusing (not impossible, just a little tricky to customize).

I haven't had the chance to really look through it yet, but why are you writing the state of the lights to localstorage? Is this like a caching for state?

**Comment by 7h30n3** [comment]
It should be possible, but then we can't use this package (https://www.npmjs.com/package/hyperion-client) anymore and have to write all by our own.
Here it's described how to control multiple devices: https://hyperion-project.org/wiki/Controlling-Multiple-Devices It isn't that easy.

What we can easily do is making the declaration of the JSON port optional. So we use the default port as long as no other is specified.

**Comment by evancohen** [comment]
Ok, that makes sense. Let's use the default port and let you specify the port optionally.

You get color persistence for free on the Hue (if the lights were blue and you turn them off and on again they should stay blue), so you should only store Hyperion light colors :)

**Comment by evancohen** [comment]
@7h30n3 are you still working on this or should I take this on?

**Comment by 7h30n3** [comment]
I have tested it and I have to say the port declaration is already optional in this commit. Therefore the new commit would just have commented out the JSON port in the example configuration file.

Also I don't think it's good to just save the settings for the Hyperion lights, because at this point in the script it is unkown on which type of LED the settings are set. Just the very last function in the script converts the settings to a LED-specific command. Because of this solution you can easily add other types of LED, e.g. Lightify from OSRAM or sending commands via UDP.

So I would say for this commit/ pull request I'm finished.

But I also have some additions in mind for other pull requests . For example if the ip address of a LED is defined as "localhost" or the name is just "mirror" the LED (behind the mirror) can lit in certain patterns up if the mirror is ready to receive a voice command or does anything else.

**Comment by evancohen** [comment]
Oh man, that's my bad. I was under the impression that it was not yet optional. I don't have any Hyperion lights, so I've been unable to test.

**Pull request merged**
