### PR TITLE
changed de-De -> de-DE

### PR DESCRIPTION
**Pull request by FrankMatheis**

### CODE REVIEW

**Comment by evancohen** [comment]
Thanks! You should remove `de-de.js` from this PR, it's an extra file. Then I'll totally merge it in :)

**Comment by evancohen** [comment]
Cool :) thanks for the README update!

**Comment by evancohen** [comment]
Awww. Shoot. This PR was onto master and I didn't catch it because I was using the phone UI. Oh well, I'll bring it into `dev` once I merge #144.

**Comment by FrankMatheis** [comment]
Sorry. I thought I made everythin correct this time :-) 
I don't know why, but the pull-request logic hasn't made it to my brain

**Pull request merged**
