### PR TITLE
Smart mirror remote

### PR DESCRIPTION
**Pull request by evancohen**
Laying down the foundation for a remote to control the smart mirror!

**Brain dump from gitter:**
> Ok, been thinking about this some more
About how the config stuff should work
it’s going to take some re-writing and some sort-of-painful UI work, but I think it’ll be worth it
So, the remote should have a searchable list of components
when you drill into a component there’s a toggle to enable it, along with some phrases with examples about how to use it
If you flip that toggle, the configuration options will appear. The benefit of this is that we can do better validation, and give people direct links to where they can get keys, etc.
You fill them out, save, and then the mirror auto-refreshes
I’d also like to come up with a better upgrade story
For now it should probably be manual
but there should be a button in the app that does it
later, once we have a better understanding about how updating should work, we can have it be automatic (or "opt-in” automatic)
even more in the future we can use the remote for o-auth for services that we just can’t get to today

### CODE REVIEW

**Comment by justbill2020** [comment]
before pulling this... can you look into adding the voice command to display the qr code? 

we can use https://www.npmjs.com/package/qrcode-npm this will move things along for the config page as well when we're ready for that...

**Comment by justbill2020** [comment]
tested this it works great however on my iphone using chrome "speak!" isn't working

it works on my desktop after allowing microphone access

toggle works as well as kiosk mode... 

might not matter but the remote page should check if currently in dev mode and check the box if its active... 

also speak should turn green after pressing the button until its complete...

**Comment by evancohen** [comment]
@justbill2020 guessing this is because you were using Safari on your iPhone? I think it doesn't support `webkitSpeechRecognition()`. Could you try Chrome? 

Maybe I should just put a text box there for a fallback?

**Comment by justbill2020** [comment]
I did try chrome... i despise safari...

in other news just added very basic QR functionality... so from the remote branch use the command "show remote link"

and then scan the code... now we have that to test config functionality... the qrcode npm library required too many additional dependencies for canvas... so this uses depreciated googleapis chart... 

https://developers.google.com/chart/infographics/docs/qr_codes?csw=1

so the qr generation needs to be revised... but check it out... the remote is ready to be pulled to the dev branch... 

I would def add a text fall back... for now... well... no lets try to figure out the issue and go from there...

**Comment by evancohen** [comment]
LOL. Those dependencies need to be taken care of: 
image

**Pull request merged**
