### PR TITLE
Motion detect

### PR DESCRIPTION
**Pull request by justbill2020**
Based on dev branch... Added python code to detect Motion on pin 26 on
raspberry pi. Spawns process in main.js... pulls vars from config.js
file.

in response to #286

really hated the name PIR-HDMI and changed to motion along with my branch name.

still having issues similar to what @missionrulz had on PR #128 where HDMI doesn't fully wake up...

### CODE REVIEW

**Comment by justbill2020** [comment]
motion detect is now working but logging during debug isn't working as well as i would like. it spits it out in the terminal emulation window not the browswer dev console.

**Comment by evancohen** [comment]
@justbill2020 you can add another IPC message between `main.js` and the service that contains the error payload (which you can then log to the console). You can look at what is there for the keyword spotter for reference.

Is that something you'd like to integrate I'm this PR or shall I merge this and then you can create another?

**Comment by justbill2020** [comment]
lets have you pull it for now... i'm working on a new build to make it better currently... that way i can keep pushing to my branch and your dev branch will have it available for testing and troubleshooting. 

either way its entirely up to you.

**Comment by evancohen** [comment]
Sure, that sounds good! One thing I just noticed is that your config vars are capitalized - to be consistent with the style of the rest of the config can you make them lower case?

If you don't have time for it today I can probably do it tonight.

Also, we are going to want to have some documentation for this. I'd be happy to write something up, but you'd probably be better suited to it since you wrote it :smile:

**Comment by justbill2020** [comment]
updated variable names to lowercase...

I will start working on some documentation for this.

**Comment by smalik03** [comment]
@justbill2020 can u please mention what PIR motion sensor are you using/recommend. It would be great if you can share a link to it. Also, I was thinking of making a security system of it, for instance, during office timing, if it detects some motion it can take a picture and send an email to you. Is that something that can be done easily? I will be glad to help put it together.

**Comment by evancohen** [comment]
@smalik03 it's documented in #325

**Comment by smalik03** [comment]
sorry my bad, @evancohen thanks

**Comment by evancohen** [comment]
Reverting this merge based on the conversation we had in gitter. A better way to integrate this will be to leverage JonnyFive

**Pull request merged**
