### PR TITLE
[CLEANUP] Apply scss-lint rules to main.scss

### PR DESCRIPTION
**Pull request by joelhawksley**
@evancohen Just thought I'd throw this out there. https://github.com/brigade/scss-lint is a pretty generally accepted standard for scss files. 

I've knocked out the low-hanging fruit on `main.scss`, and am happy to do the same for `icesnow.scss`.

### CODE REVIEW

**Comment by kurtdb** [comment]
It would also be handy if you throw the check into the bower-file, so we can cover this in the future.

**Comment by joelhawksley** [comment]
@kurtdb I was actually wondering what the local dev workflow was for styles... there is no prescribed `sass --watch`.

Typically, these types of checks are either done at commit-time with something like Overcommit, in addition to on CI. We could probably setup a free Travis instance to do the check on each PR automatically (something I'd be happy to do, cc @evancohen)

**Comment by evancohen** [comment]
@joelhawksley this is awesome dude :+1: thanks for putting this together! We haven't been using SCSS... It got added a while ago, but people kept sending PRs with just CSS so I stopped using it to save time. There is already a [travis branch](https://github.com/evancohen/smart-mirror/tree/travis) that you could take a look at, although it's quite out of date. 

@kurtdb and I have talked about integrating testing via travis but haven't pulled the trigger yet - if you sent a pull request for it we'd appreciate it!

In terms of dev workflow I think it'd be nice to set up something with livereload if we are going to go that route (although I've never actually tried this with SCSS). Ideally livereload would only be injected when the mirror is launched with the `dev` flag (resources are very limited on the Pi so we should conserve them wherever possible).

**Comment by kurtdb** [comment]
I'll put adding jslint/jshint to my todo. Normally livereloading should be enabled in my jasmine-branch, but that's also very outdated. Maybe someone can cherrypick some stuff from there?

**Comment by joelhawksley** [comment]
@evancohen interesting. Based on my initial experience patching the CSS for my personal use, I don't think it'd be a big deal to just drop the SCSS entirely. That would keep the local dev project simple, avoiding the need for any build tools. 

If not, I'd advocate for updating the SCSS (which will be tricky at this point, given that it's not been used in a while) and taking the CSS out of source control, so there is a single committed source of truth for styles.

**Comment by evancohen** [comment]
Agreed, that would certainly be the simpler thing to do. The mirror is actually pretty straightforward in terms of stylistic complexity. I've created #300 to track this.

Maybe we could at using a CSS linter with [overcommit](https://github.com/brigade/overcommit)?

**Pull request closed without merging**
